<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17343" started-at="2018-10-14T18:19:16Z" finished-at="2018-10-14T18:19:34Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17343" started-at="2018-10-14T18:19:16Z" finished-at="2018-10-14T18:19:34Z">
      <class name="seleniumpractice.Example2">
        <test-method status="PASS" signature="setUp()[pri:0, instance:seleniumpractice.Example2@6a4f787b]" name="setUp" is-config="true" duration-ms="15881" started-at="2018-10-14T18:19:16Z" finished-at="2018-10-14T18:19:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="checkSameObjectLocators()[pri:0, instance:seleniumpractice.Example2@6a4f787b]" name="checkSameObjectLocators" duration-ms="101" started-at="2018-10-14T18:19:32Z" finished-at="2018-10-14T18:19:32Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at seleniumpractice.Example2.checkSameObjectLocators(Example2.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkSameObjectLocators -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:seleniumpractice.Example2@6a4f787b]" name="tearDown" is-config="true" duration-ms="1291" started-at="2018-10-14T18:19:32Z" finished-at="2018-10-14T18:19:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=checkSameObjectLocators status=FAILURE method=Example2.checkSameObjectLocators()[pri:0, instance:seleniumpractice.Example2@6a4f787b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- seleniumpractice.Example2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
